SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE tb_book_status;
TRUNCATE TABLE tb_book_restriction;
TRUNCATE TABLE tb_book_license;

ALTER TABLE tb_book_status MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE tb_book_restriction MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE tb_book_license MODIFY COLUMN id INT AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS = 1;